/**
 * Auto-generated WORKSPACE.md — a living project summary injected into the
 * system prompt. Detects tech stack, directory layout, entry points and recent
 * git activity. The user may edit it; regeneration preserves a manual section.
 */
import { readFile, writeFile, listDir, isTauri } from './tauri';

const MANUAL_MARKER = '<!-- APEX:MANUAL -->';

function sep(workspace: string) { return workspace.includes('\\') ? '\\' : '/'; }
function join(workspace: string, ...parts: string[]) {
  return [workspace, ...parts].join(sep(workspace));
}

interface PackageJson {
  name?: string; version?: string; description?: string;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  scripts?: Record<string, string>;
}

async function tryRead(path: string): Promise<string | null> {
  try { return await readFile(path); } catch { return null; }
}

async function detectStack(workspace: string): Promise<string[]> {
  const stack: string[] = [];
  const pkgRaw = await tryRead(join(workspace, 'package.json'));
  if (pkgRaw) {
    try {
      const pkg = JSON.parse(pkgRaw) as PackageJson;
      const deps = { ...pkg.dependencies, ...pkg.devDependencies };
      const has = (n: string) => Object.keys(deps).some(d => d === n || d.startsWith(n));
      if (has('react')) stack.push('React');
      if (has('vue')) stack.push('Vue');
      if (has('svelte')) stack.push('Svelte');
      if (has('next')) stack.push('Next.js');
      if (has('vite')) stack.push('Vite');
      if (has('typescript')) stack.push('TypeScript');
      if (has('tailwindcss')) stack.push('Tailwind CSS');
      if (has('@tauri-apps/api')) stack.push('Tauri');
      if (has('express')) stack.push('Express');
      if (has('zustand')) stack.push('Zustand');
    } catch { /* malformed package.json */ }
  }
  if (await tryRead(join(workspace, 'Cargo.toml'))) stack.push('Rust (Cargo)');
  if (await tryRead(join(workspace, 'go.mod'))) stack.push('Go');
  if (await tryRead(join(workspace, 'requirements.txt')) || await tryRead(join(workspace, 'pyproject.toml'))) stack.push('Python');
  if (await tryRead(join(workspace, 'pom.xml'))) stack.push('Java (Maven)');
  return [...new Set(stack)];
}

async function detectEntryPoints(workspace: string): Promise<string[]> {
  const candidates = [
    'src/main.tsx', 'src/main.ts', 'src/index.tsx', 'src/index.ts',
    'src/App.tsx', 'index.html', 'src/main.rs', 'src-tauri/src/main.rs',
    'main.py', 'src/main.py', 'cmd/main.go', 'main.go',
  ];
  const found: string[] = [];
  for (const c of candidates) {
    if (await tryRead(join(workspace, ...c.split('/')))) found.push(c);
  }
  return found;
}

async function dirSummary(workspace: string): Promise<string> {
  try {
    const entries = await listDir(workspace);
    const dirs = entries.filter(e => e.is_dir && !e.name.startsWith('.') && e.name !== 'node_modules' && e.name !== 'target');
    const files = entries.filter(e => !e.is_dir && !e.name.startsWith('.'));
    const lines: string[] = [];
    for (const d of dirs.slice(0, 20)) lines.push(`- \`${d.name}/\``);
    for (const f of files.slice(0, 12)) lines.push(`- \`${f.name}\``);
    return lines.join('\n');
  } catch {
    return '(unavailable)';
  }
}

async function recentCommits(workspace: string): Promise<string> {
  if (!isTauri()) return '';
  try {
    const { invoke } = await import('@tauri-apps/api/core');
    const log = await invoke<unknown>('git_log', { workspace, limit: 20 });
    if (Array.isArray(log)) {
      return log.slice(0, 20).map((c) => {
        const o = c as { hash?: string; author?: string; message?: string; date?: string };
        return `- \`${(o.hash ?? '').slice(0, 7)}\` ${o.message ?? ''}${o.author ? ` — ${o.author}` : ''}`;
      }).join('\n');
    }
    return '';
  } catch {
    return '';
  }
}

export async function generateWorkspaceMd(workspace: string): Promise<string> {
  const name = workspace.split(/[\\/]/).pop() ?? workspace;
  const [stack, entries, structure, commits] = await Promise.all([
    detectStack(workspace),
    detectEntryPoints(workspace),
    dirSummary(workspace),
    recentCommits(workspace),
  ]);

  // Preserve manual section if it exists
  let manual = '';
  const existing = await tryRead(join(workspace, '.ai', 'WORKSPACE.md'));
  if (existing) {
    const idx = existing.indexOf(MANUAL_MARKER);
    if (idx >= 0) manual = existing.slice(idx);
  }

  const md = `# ${name} — Workspace Memory

*Auto-generated by APEX. Edit the manual section at the bottom; it is preserved on regeneration.*

## Tech Stack
${stack.length ? stack.map(s => `- ${s}`).join('\n') : '- (not detected)'}

## Project Structure
${structure}

## Entry Points
${entries.length ? entries.map(e => `- \`${e}\``).join('\n') : '- (not detected)'}
${commits ? `\n## Recent Activity (last 20 commits)\n${commits}\n` : ''}
${manual || `${MANUAL_MARKER}\n## Notes\n_Add project-specific notes here. APEX will keep this section._\n`}`;

  try {
    await writeFile(join(workspace, '.ai', 'WORKSPACE.md'), md);
  } catch { /* browser preview — can't write */ }

  return md;
}

export async function loadWorkspaceMd(workspace: string): Promise<string | null> {
  return tryRead(join(workspace, '.ai', 'WORKSPACE.md'));
}
